# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget mapserver)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target mapserver
add_library(mapserver SHARED IMPORTED)

# Import target "mapserver" for configuration "Debug"
set_property(TARGET mapserver APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(mapserver PROPERTIES
  IMPORTED_IMPLIB_DEBUG "K:/Development/op3d_active/mapserver-7.4.2/msvc/Debug/mapserver.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "K:/Development/op3d_active/libpng-1.4.3/projects/vstudio/vc110/Win32/Release/libpng14.lib;K:/Development/op3d_active/jpeg-9/vc141/Win32/vs2017_Release/jpeg.lib;K:/Development/op3d_active/freetype-2.6.3/builds/win32/vc2012/vc110/Win32/vs2012_Release/freetype250.lib;K:/Development/op3d_active/Proj-4.9.0/vc141/Win32/vs2017_Release/proj.lib;K:/Development/op3d_active/protobuf-3.7.1/msvc/vc141/Win32/vs2017_Release/protobuf-c.lib;C:/Development/op3d_active/pixman-0.32.2/vc141/Win32/vs2017_Release/pixman-1.lib;K:/Development/op3d_active/fribidi-0.19.6/visual/vc141/Win32/vs2017_Release/fribidi.lib;K:/Development/op3d_active/harfbuzz-2.4.0/msvc/vc141/Win32/vs2017_Release/harfbuzz.lib;K:/Development/op3d_active/libiconv-1.12/MSVC11/vc141/Win32/vs2017_Release/libiconv.lib;K:/Development/op3d_active/cairo-1.12.16/vc141/Win32/vs2017_Release/cairo.lib;K:/Development/op3d_active/geos-3.5.0/msvc/vc141/Win32/vs2017_Release/geos.lib;K:/Development/op3d_active/postgresql-9.3.2/vc141/Win32/vs2017_Release/libpq.lib;K:/Development/op3d_active/gdal-2.4.0/vc141/x64/vs2017_Release/gdal_i.lib;K:/Development/op3d_active/curl-7.63.0/msvc/lib/vc110/Win32/Release/libcurl_imp.lib;K:/Development/op3d_active/libxml2-2.7.7/win32/vc110/Win32/Release/libxml2.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libxslt.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libexslt.lib;K:/Development/op3d_active/giflib-5.0.4/build.vc11/vc110/Win32/vs2012_Release/libgiflib-5.0.4.lib;ws2_32.lib"
  IMPORTED_LOCATION_DEBUG "K:/Development/op3d_active/mapserver-7.4.2/msvc/Debug/mapserver.dll"
  )

# Import target "mapserver" for configuration "Release"
set_property(TARGET mapserver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mapserver PROPERTIES
  IMPORTED_IMPLIB_RELEASE "K:/Development/op3d_active/mapserver-7.4.2/msvc/Release/mapserver.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "K:/Development/op3d_active/libpng-1.4.3/projects/vstudio/vc110/Win32/Release/libpng14.lib;K:/Development/op3d_active/jpeg-9/vc141/Win32/vs2017_Release/jpeg.lib;K:/Development/op3d_active/freetype-2.6.3/builds/win32/vc2012/vc110/Win32/vs2012_Release/freetype250.lib;K:/Development/op3d_active/Proj-4.9.0/vc141/Win32/vs2017_Release/proj.lib;K:/Development/op3d_active/protobuf-3.7.1/msvc/vc141/Win32/vs2017_Release/protobuf-c.lib;C:/Development/op3d_active/pixman-0.32.2/vc141/Win32/vs2017_Release/pixman-1.lib;K:/Development/op3d_active/fribidi-0.19.6/visual/vc141/Win32/vs2017_Release/fribidi.lib;K:/Development/op3d_active/harfbuzz-2.4.0/msvc/vc141/Win32/vs2017_Release/harfbuzz.lib;K:/Development/op3d_active/libiconv-1.12/MSVC11/vc141/Win32/vs2017_Release/libiconv.lib;K:/Development/op3d_active/cairo-1.12.16/vc141/Win32/vs2017_Release/cairo.lib;K:/Development/op3d_active/geos-3.5.0/msvc/vc141/Win32/vs2017_Release/geos.lib;K:/Development/op3d_active/postgresql-9.3.2/vc141/Win32/vs2017_Release/libpq.lib;K:/Development/op3d_active/gdal-2.4.0/vc141/x64/vs2017_Release/gdal_i.lib;K:/Development/op3d_active/curl-7.63.0/msvc/lib/vc110/Win32/Release/libcurl_imp.lib;K:/Development/op3d_active/libxml2-2.7.7/win32/vc110/Win32/Release/libxml2.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libxslt.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libexslt.lib;K:/Development/op3d_active/giflib-5.0.4/build.vc11/vc110/Win32/vs2012_Release/libgiflib-5.0.4.lib;ws2_32.lib"
  IMPORTED_LOCATION_RELEASE "K:/Development/op3d_active/mapserver-7.4.2/msvc/Release/mapserver.dll"
  )

# Import target "mapserver" for configuration "MinSizeRel"
set_property(TARGET mapserver APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(mapserver PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "K:/Development/op3d_active/mapserver-7.4.2/msvc/MinSizeRel/mapserver.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "K:/Development/op3d_active/libpng-1.4.3/projects/vstudio/vc110/Win32/Release/libpng14.lib;K:/Development/op3d_active/jpeg-9/vc141/Win32/vs2017_Release/jpeg.lib;K:/Development/op3d_active/freetype-2.6.3/builds/win32/vc2012/vc110/Win32/vs2012_Release/freetype250.lib;K:/Development/op3d_active/Proj-4.9.0/vc141/Win32/vs2017_Release/proj.lib;K:/Development/op3d_active/protobuf-3.7.1/msvc/vc141/Win32/vs2017_Release/protobuf-c.lib;C:/Development/op3d_active/pixman-0.32.2/vc141/Win32/vs2017_Release/pixman-1.lib;K:/Development/op3d_active/fribidi-0.19.6/visual/vc141/Win32/vs2017_Release/fribidi.lib;K:/Development/op3d_active/harfbuzz-2.4.0/msvc/vc141/Win32/vs2017_Release/harfbuzz.lib;K:/Development/op3d_active/libiconv-1.12/MSVC11/vc141/Win32/vs2017_Release/libiconv.lib;K:/Development/op3d_active/cairo-1.12.16/vc141/Win32/vs2017_Release/cairo.lib;K:/Development/op3d_active/geos-3.5.0/msvc/vc141/Win32/vs2017_Release/geos.lib;K:/Development/op3d_active/postgresql-9.3.2/vc141/Win32/vs2017_Release/libpq.lib;K:/Development/op3d_active/gdal-2.4.0/vc141/x64/vs2017_Release/gdal_i.lib;K:/Development/op3d_active/curl-7.63.0/msvc/lib/vc110/Win32/Release/libcurl_imp.lib;K:/Development/op3d_active/libxml2-2.7.7/win32/vc110/Win32/Release/libxml2.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libxslt.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libexslt.lib;K:/Development/op3d_active/giflib-5.0.4/build.vc11/vc110/Win32/vs2012_Release/libgiflib-5.0.4.lib;ws2_32.lib"
  IMPORTED_LOCATION_MINSIZEREL "K:/Development/op3d_active/mapserver-7.4.2/msvc/MinSizeRel/mapserver.dll"
  )

# Import target "mapserver" for configuration "RelWithDebInfo"
set_property(TARGET mapserver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(mapserver PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "K:/Development/op3d_active/mapserver-7.4.2/msvc/RelWithDebInfo/mapserver.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "K:/Development/op3d_active/libpng-1.4.3/projects/vstudio/vc110/Win32/Release/libpng14.lib;K:/Development/op3d_active/jpeg-9/vc141/Win32/vs2017_Release/jpeg.lib;K:/Development/op3d_active/freetype-2.6.3/builds/win32/vc2012/vc110/Win32/vs2012_Release/freetype250.lib;K:/Development/op3d_active/Proj-4.9.0/vc141/Win32/vs2017_Release/proj.lib;K:/Development/op3d_active/protobuf-3.7.1/msvc/vc141/Win32/vs2017_Release/protobuf-c.lib;C:/Development/op3d_active/pixman-0.32.2/vc141/Win32/vs2017_Release/pixman-1.lib;K:/Development/op3d_active/fribidi-0.19.6/visual/vc141/Win32/vs2017_Release/fribidi.lib;K:/Development/op3d_active/harfbuzz-2.4.0/msvc/vc141/Win32/vs2017_Release/harfbuzz.lib;K:/Development/op3d_active/libiconv-1.12/MSVC11/vc141/Win32/vs2017_Release/libiconv.lib;K:/Development/op3d_active/cairo-1.12.16/vc141/Win32/vs2017_Release/cairo.lib;K:/Development/op3d_active/geos-3.5.0/msvc/vc141/Win32/vs2017_Release/geos.lib;K:/Development/op3d_active/postgresql-9.3.2/vc141/Win32/vs2017_Release/libpq.lib;K:/Development/op3d_active/gdal-2.4.0/vc141/x64/vs2017_Release/gdal_i.lib;K:/Development/op3d_active/curl-7.63.0/msvc/lib/vc110/Win32/Release/libcurl_imp.lib;K:/Development/op3d_active/libxml2-2.7.7/win32/vc110/Win32/Release/libxml2.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libxslt.lib;K:/Development/op3d_active/libxslt-1.1.28/win32/vc110/Win32/vs2012_Release/libexslt.lib;K:/Development/op3d_active/giflib-5.0.4/build.vc11/vc110/Win32/vs2012_Release/libgiflib-5.0.4.lib;ws2_32.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "K:/Development/op3d_active/mapserver-7.4.2/msvc/RelWithDebInfo/mapserver.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
